import localFont from 'next/font/local'
import './globals.css'

const myFont = localFont({
  src: './font/Inter-VariableFont_slnt,wght.ttf',
  display: 'swap',
})

export const metadata = {
  title: "Andrew Larson's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>        
        {children}
      </body>
    </html>
  )
}
